In [ ]:
element = 'oxygen'

print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
#Challenge 1
print('value of element[:4]:', element[:4])
print('value of element[4:]:', element[4:])
print('value of element[:]:', element[:])
#Challenge 2
print('value of element[-1]:', element[-1])
print('value of element[-2]:', element[-2])
#Challenge 3_Ans: element[1:-1] element[1:-1] gives you all characters except the first and the last one.
#Challenge 4_Ans:
element = 'helium'
print('last three characters:', element[-3:])
element = 'carpentry'
print('last three characters:', element[-3:])
element = 'clone'
print('last three characters:', element[-3:])
element = 'hi'
print('last three characters:', element[-3:])
#Challenge 5 (STACKING ARRAYS):
import numpy

A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)
D = numpy.hstack((A[:, :1], A[:, -1:]))
print('D = ')
print(D)






first three characters: oxy
last three characters: gen
value of element[:4]: oxyg
value of element[4:]: en
value of element[:]: oxygen
value of element[-1]: n
value of element[-2]: e
last three characters: ium
last three characters: try
last three characters: one
last three characters: hi
A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
D = 
[[1 3]
 [4 6]
 [7 9]]


In [ ]:
n_terms = 10
# First two terms of the Fibonacci sequence
a, b = 0, 1
print("Fibonacci sequence:")
for _ in range(n_terms):
    print(a, end=' ')
    a, b = b, a + b

Fibonacci sequence:
0 1 1 2 3 5 8 13 21 34 